---
- name: ensure python mysql package is installed
  apt:
    pkg: "{{ etherpad_python_mysql_package }}"
    state: present

- name: ensure mysql database is present
  mysql_db:
    name: "{{ etherpad_mysql_database_name }}"
    collation: "{{ etherpad_mysql_database_collation }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  register: database

- name: ensure mysql schema is present
  template:
    src: schema.sql.j2
    dest: /tmp/etherpad_schema.sql
    mode: 0755
  when: database is changed

- name: ensure mysql database is present
  mysql_db:
    name: "{{ etherpad_mysql_database_name }}"
    collation: "{{ etherpad_mysql_database_collation }}"
    state: import
    target: /tmp/etherpad_schema.sql
    login_unix_socket: /run/mysqld/mysqld.sock
  when: database is changed

- name: ensure database schema is absent after import
  file:
    path: /tmp/etherpad_schema.sql
    state: absent
  when: database is changed

- name: Fail if mysql user has no password
  fail:
    msg: "You need to set a password for mysql user!"
  when: etherpad_mysql_database_password is undefined or etherpad_mysql_database_password|length == 0

- name: ensure mysql user is present
  mysql_user:
    name: "{{ etherpad_mysql_database_user }}"
    state: present
    password: "{{ etherpad_mysql_database_password }}"
    priv: "{{ etherpad_mysql_database_user }}.*:ALL"
    login_unix_socket: /run/mysqld/mysqld.sock
